import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { ComboxboxMultiSelect } from "../components/ComboboxMultiSelect";
// import Image from 'next/image'
import styles from "../styles/Home.module.css";

const recipes = [
  {
    label: "Pizza med grönkål och pumpatopping",
    value: "pizza-med-gronkal-och-pumpatopping",
  },
  {
    label: "Griljerad seitan till julbordet",
    value: "griljerad-seitan-till-julbordet",
  },
];

const Home: NextPage = () => {
  const [ingredients, setIngredients] = React.useState<any[]>([]);
  const [selectedRecipes, setSelectedRecipes] = React.useState<string[]>([]);

  const accumulate = async (event: React.SyntheticEvent) => {
    event.preventDefault();
    const queryParameters = new URLSearchParams();
    selectedRecipes.forEach((sr) => queryParameters.append("urls", sr));
    const response = await fetch(
      `/.netlify/functions/accumulator?${queryParameters.toString()}`
    );
    const json = await response.json();
    setIngredients(json);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Inköpslistegenerator - Portionen under tian</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Skapa inköpslistor utifrån recept från{" "}
          <a href="https://undertian.com/">Portionen under tian</a>
        </h1>

        <form onSubmit={accumulate}>
          <ComboxboxMultiSelect
            options={recipes}
            setSelectedValues={setSelectedRecipes}
          />
          <button>Hämta ingredienslista</button>
        </form>

        <ul>
          {ingredients.map(({ name, amount, unit }) => (
            <li key={`${name}${unit}`}>
              {name}: {amount} {unit}
            </li>
          ))}
        </ul>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
