import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [ingredients, setIngredients] = React.useState<any[]>([]);

  const accumulate = async (event: React.SyntheticEvent) => {
    const target = event.currentTarget as typeof event.currentTarget & {
      url1: { value: string }
    }
    event.preventDefault()
    const queryParameters = new URLSearchParams()
    queryParameters.append("urls", target.url1.value)
    const response = await fetch(`/.netlify/functions/accumulator?${queryParameters.toString()}`)
    const json = await response.json()
    setIngredients(json)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Inköpslistegenerator - Portionen under tian</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Skapa inköpslistor utifrån recept från <a href="https://undertian.com/">Portionen under tian</a>
        </h1>
      
      <form onSubmit={accumulate}>
        <label>URL till recept
          {/* TODO: Multiple urls */}
          {/* TODO: Nice selector, maybe autocomplete based on known URLs. How can we know? */}
          <input name="url1" />
        </label>
        </form>
        
      <ul>{
        ingredients.map(({name, amount, unit}) => <li key={`${name}${unit}`}>{name}: {amount} {unit}</li>)
}</ul>

      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home
